image: matthem0730/gitpod-workspace:1.0.0

tasks:
  - name: Setup Project
    before: sh .gitpod/setup.sh
    init: |
      npm install
      cd frontend && npm install
    command: npm run dev

ports:
  - port: 27017
    onOpen: ignore
    visibility: public
  - port: 5000
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - zhuangtongfa.material-theme
    - vscode-icons-team.vscode-icons
    - formulahendry.auto-close-tag
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - christian-kohler.npm-intellisense
    - ms-azuretools.vscode-docker
    - dsznajder.es7-react-js-snippets
    - mongodb.mongodb-vscode
