image: matthem0730/gitpod-workspace:1.0.0

tasks:
  - name: Setup Project
    before: sh .gitpod/setup.sh
    init: npm install
    command: npm run server

ports:
  - port: 27017
    onOpen: ignore
    visibility: private
  - port: 5001
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - zhuangtongfa.material-theme
    - vscode-icons-team.vscode-icons
    - formulahendry.auto-close-tag
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - christian-kohler.npm-intellisense
    - ms-azuretools.vscode-docker
    - dsznajder.es7-react-js-snippets
    - mongodb.mongodb-vscode
    - rangav.vscode-thunder-client
